"""Answer banks: one healthy answer set for each component. Cases override nodes."""

HEALTHY = {
    "battery": {
        "q_bat_start": "not sure it's the battery, it cranks normally",
        "q_bat_terminals": "no, clean and tight",
        "q_bat_drain": "25 mA once it's asleep",
        "q_bat_terminal_drop": "no, 0.1 V across each clamp",
        "q_bat_voltage": "12.6 V at rest",
        "q_bat_alt_unplug": "no, drain doesn't change with the B+ off",
        "q_bat_charge_test": "yes, passes the load test",
        "q_bat_history": "no, never gone flat on its own",
        "q_bat_age": "no, 2 years old, tester says 92% health",
        "q_bat_cell": "no, holds 12.7 V overnight",
    },
    "alternator": {
        "q_alt_symptom": "not sure, no warning light and no squeal",
        "q_alt_run_voltage": "14.1 V at 2000 with the headlights on",
        "q_alt_belt": "no, belt's in good nick and quiet",
        "q_alt_ripple": "no, 0.1 V AC",
        "q_alt_belt_test": "n/a, belt didn't need touching",
        "q_alt_field": "yes, 12.3 V at the D+ terminal",
        "q_alt_diode_drain": "no, 25 mA asleep",
        "q_alt_drain_unplug": "n/a, drain is only 25 mA anyway",
        "q_alt_output": "no, 102 A on a 110 A unit",
    },
    "starter": {
        "q_sta_symptom": "not sure, it cranks normally",
        "q_sta_lights": "yes, headlights stay bright",
        "q_sta_noise": "no, 150 A and no grind",
        "q_sta_tap": "no, tapping it changes nothing",
        "q_sta_solenoid_volt": "yes, 11.2 V at the trigger wire",
        "q_sta_battery_volt": "yes, 12.6 V",
        "q_sta_bench": "no, spins fine on the bench",
        "q_sta_output_volt": "yes, 10.8 V at the motor terminal",
    },
    "fuel_pump": {
        "q_fp_symptom": "not sure, the engine runs",
        "q_fp_prime": "yes, pump primes for 2 s",
        "q_fp_pressure_idle": "yes, 3.5 bar at idle, on spec",
        "q_fp_pressure_crank": "at spec, 3.4 bar while cranking",
        "q_fp_relay": "yes, 12.1 V at the pump plug",
        "q_fp_pressure_load": "holds 3.5 bar flat out",
        "q_fp_filter_age": "no, filter changed 12,000 km ago",
        "q_fp_pump_current": "no, pump runs and draws 5 A",
        "q_fp_filter_swap": "n/a, filter's new",
        "q_fp_volume": "no, 700 ml in 30 s, spec is 650",
    },
    "injectors": {
        "q_inj_symptom": "not sure, no misfire or mixture codes stored",
        "q_inj_coil_swap": "no, nothing to swap, no misfire",
        "q_inj_pressure_load": "holds 3.5 bar at full load",
        "q_inj_balance": "no, all four within 3%",
        "q_inj_trim": "+2% long term",
        "q_inj_click": "no, they all click the same",
        "q_inj_smoke": "no, intake's tight",
        "q_inj_leak": "no, doesn't drip",
        "q_inj_flow": "no, all within 95% of rated flow",
    },
    "ignition": {
        "q_ign_symptom": "not sure, it runs smooth and there are no codes",
        "q_ign_one_cyl": "no, no misfire codes at all",
        "q_ign_rpm": "no, reads 230 rpm cranking",
        "q_ign_coil_swap": "no, nothing moves",
        "q_ign_plugs": "good, changed 15,000 km ago",
        "q_ign_code": "no, no crank sensor codes",
        "q_ign_coil_check": "no, coils measure in spec",
        "q_ign_plug_one": "no, plug looks fine",
        "q_ign_plug_swap": "no, plugs are fresh anyway",
        "q_ign_crank_signal": "no, clean signal on the scope",
    },
    "cooling_fan": {
        "q_fan_when": "not sure, it hasn't overheated here",
        "q_fan_runs": "yes, fan kicks in at 98 °C",
        "q_fan_top_hose": "no, top hose is hot",
        "q_fan_fuse": "no, fuse is good",
        "q_fan_motor_current": "no, spins freely, 8 A",
        "q_fan_direct": "yes, runs on 12 V direct",
        "q_fan_relay_click": "yes, clicks and gives 12 V",
    },
    "thermostat": {
        "q_th_symptom": "not sure, the gauge sits in the middle",
        "q_th_top_hose": "no, top hose is hot",
        "q_th_warm_time": "no, 90 °C after 10 min",
        "q_th_temp_diff": "no, only a few degrees",
        "q_th_fan": "yes, fan cycles on and off",
        "q_th_radiator_warm": "no, stays cold until it opens at 88",
        "q_th_bench": "no, opens at 88 °C",
        "q_th_sensor": "yes, sensor agrees with the IR gun",
    },
    "water_pump": {
        "q_wp_symptom": "not sure, level's on max and no smoke",
        "q_wp_visible": "no, holds 1.2 bar for 15 min",
        "q_wp_combustion": "no, fluid stays blue",
        "q_wp_flow": "no, both hoses hot",
        "q_wp_leak_place": "not sure, no leak found",
        "q_wp_leakdown": "no, no air in the coolant",
        "q_wp_impeller": "no, impeller's fine",
        "q_wp_weep": "no, weep hole dry",
        "q_wp_hose_check": "no, hoses are firm",
        "q_wp_clamp": "no, clamps are tight",
    },
    "brakes": {
        "q_brk_symptom": "not sure, brakes feel normal",
        "q_brk_pads": "8 mm front, 6 mm rear",
        "q_brk_runout": "0.02 mm",
        "q_brk_wheel_temp": "no, all four about the same",
        "q_brk_pump": "no, pedal's firm from the start",
        "q_brk_hub_clean": "no, run-out is fine",
        "q_brk_wheel_spin": "no, all spin free",
        "q_brk_bleed": "no, clean fluid only",
        "q_brk_fluid_leak": "no, level on max and no leaks",
        "q_brk_abs_test": "no, valve test normal",
    },
    "abs": {
        "q_abs_codes": "not sure, no ABS codes stored",
        "q_abs_live": "no, all four speeds agree",
        "q_abs_pump_run": "yes, runs on the actuator test",
        "q_abs_play": "no, tight and smooth",
        "q_abs_valves": "no, all channels pass",
        "q_abs_pump_power": "yes, 12.4 V at the fuse and the plug",
        "q_abs_sensor": "no, sensors in spec",
    },
    "wheel_bearings": {
        "q_whl_noise": "not sure, no noise from the wheels",
        "q_whl_load": "no, no hum to change",
        "q_whl_cv_test": "no, no clicks in tight circles",
        "q_whl_play": "no, no play",
        "q_whl_spin": "no, all turn smooth",
        "q_whl_boot": "no, boots intact",
        "q_whl_sensor": "no, sensors in spec",
        "q_whl_cv_play": "no, no play at the outer joints",
    },
    "can_bus": {
        "q_can_symptom": "not sure, no warning lights",
        "q_can_codes": "no, no U codes stored",
        "q_can_ecu_supply": "yes, 12.3 V at the ECU plug",
        "q_can_resistance": "60 Ω across pins 6 and 14",
        "q_can_gateway": "no, gateway self-test passes",
        "q_can_wiring": "no, harness is clean and dry",
        "q_can_scope": "no, clean CAN signal",
    },
    "ecu": {
        "q_ecu_symptom": "not sure, no security light and the ECU talks fine",
        "q_ecu_immo_code": "no, no immobiliser codes",
        "q_ecu_supply": "yes, 12.4 V supply and 0.04 V ground drop",
        "q_ecu_antenna": "no, antenna reads the key",
        "q_ecu_can_resistance": "yes, 60 Ω",
        "q_ecu_main_relay": "no, relay and fuses good",
        "q_ecu_internal": "no, ECU responds normally",
        "q_ecu_supply_wire": "no, drops are small",
    },
    "clutch": {
        "q_clu_symptom": "not sure, clutch bites normally",
        "q_clu_stall_test": "no, stalls straight away",
        "q_clu_fluid": "no, level's fine and it's dry",
        "q_clu_rattle": "no, no rattle",
        "q_clu_adjust": "yes, free play in spec",
        "q_clu_bleed": "no, pedal firm",
        "q_clu_dmf_play": "no, in spec",
        "q_clu_judder": "no, pulls away smooth",
    },
    "exhaust": {
        "q_exh_symptom": "not sure, exhaust sounds normal",
        "q_exh_smoke_test": "no, no leaks",
        "q_exh_backpressure": "no, 1.1 psi at 2500",
        "q_exh_o2_code": "no, no O2 codes",
        "q_exh_cat_temp": "no, outlet hotter than the inlet",
        "q_exh_o2_switch": "no, switches normally",
        "q_exh_cat_compare": "no, downstream stays steady",
        "q_exh_leak_before": "no, no leak before the sensor",
    },
}
